### ISSUE TITLE
Script dies early on. Or connection error when workaround install.

### ISSUE THREAD

**Issue by ev0net** [BurakBoz/cyberpanel-on-wsl2#1]
Hi. Thanks for your work on this. 

Trying to set up a local development environment on WIN11 to more closely match my production server. I've tried a few things but I can't get this script to work. If following instructions exactly, script dies (terminal window closes early on). If manually running install.sh via manual AlmaLinux WSL install, the script will go all the way through, but then I get 127.0.0.1 refused to connect errors in browser for https://127.0.0.1:8090/

Any thoughts? Thanks!

**Comment by BurakBoz** [comment]
Hi,

1. Run cmd.exe as administrator
2. go in that folder with cd command
3. run install.bat file from that window.

Follow instructions for terminal output.
Reboot and try again if fails installation.

I've just tested and it works on fresh windows 11 installation. 
If you're using customized iso version of windows you may try official windows installation iso.

If still not works share your terminal output

**Comment by BurakBoz** [comment]
Hi,

Run cmd.exe as administrator
go in that folder with cd command
run install.bat file from that window.
Follow instructions on terminal output.
Reboot and try again if fails installation.

I've just tested and it works on fresh windows 11 installation.
If you're using customized iso version of windows you may try official windows installation iso.

If still not works share your terminal output

Oh, also if you get 500 error run restart-cyberpanel.bat

**Comment by ev0net** [comment]
Thanks. Re-running it from admin cmd did the trick. Maybe add that to the documentation?

FYI: My OS is official W11 install a month ago.

Also: Tried with Rocky Linux 8: replaced file reference in install.bat to downloaded rocky 8 rootfs file. Install completed but panel would not work. I thought it might given they are so closely related. Any thoughts?

**Comment by BurakBoz** [comment]
You're welcome. 
CyberPanel is a combination bunch of services like mysql, litespeed etc.
You need to install systemd on wsl linux distros in order to run any linux services like lscpd lsws mysqld etc. That's why.
